spring:
  r2dbc:
    url: r2dbc:postgres://localhost:5432/lightDigitalTest
    username: postgres
    password: ItsMyLife0203
  flyway:
    url: jdbc:postgresql://localhost:5432/lightDigitalTest
    user: postgres
    password: ItsMyLife0203
    locations: classpath:db.migration
  jpa:
    show-sql: true
#    generate-ddl: true
#    hibernate:
#      ddl-auto: update

